### ISSUE TITLE
fortls starts in wrong directory

### ISSUE THREAD

**Issue by kc9jud** [hansec/vscode-fortran-ls#10]
Hello,

I'm seeing `fortls` launching in the wrong directory when using a multiroot workspace. However, unlike #5, I'd like separate fortls instances for separate roots -- I have a couple different codes, and I don't want bleed-over between them... however, it seems as if right now, fortls always launches in the first directory of the workspace. Is there a way to change this, or is a simple addition?

Cheers,
Patrick

**Comment by hansec** [comment]
Thanks for the suggestion. I just added support for this feature in master and will include it in the next release. As implemented, a separate language server will be launched for each "root" so all the projects should be isolated from the perspective of suggestions, references, etc.

**Comment by kc9jud** [comment]
Perfect, thank you!
