### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by bmxam** [hansec/vscode-fortran-ls#11]
[Boy.txt](https://github.com/hansec/vscode-fortran-ls/files/3060461/Boy.txt)
[Human.txt](https://github.com/hansec/vscode-fortran-ls/files/3060462/Human.txt)

Dear Chris,

Here is a new suggestion. It is quite difficult to explain so don't hesitate to go directly to the example... When using _Go to Definition_ on a procedure that is declared in a derived type, this derived type being defined in an other file, we are sent to the line `procedure, pass(this) :: foo`. Most of the time, we would like to go directly to the procedure body itself  `subroutine foo(..)`.

I attached a minimum working example (attached files are _.f90_ files). `Human` declares a procedure `foo`. `Boy` extends `Human` and uses the procedure `foo` somewhere. When using _Go to Definition_ on `foo` in line 16 of Boy.f90, we are sent to line 7 of Human.f90. We could expect to be sent directly to line 12 of Human.f90 (the subroutine body).
Even better, to satisfy "everybody" : clicking on `foo` in line 16 of Boy.f90 could redirect (as it is the case now) to line 7 of Human.f90 but then clicking on `foo` in line 7 of Human.f90 could redirect to the subroutine body, line 12.

I hope my example will help you understand the behaviour I am describing.

Best regards,

Maxime

**Comment by hansec** [comment]
This feature is already implemented as a separate request "[Go to Implementation](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-implementation)" in VSCode. By default the key mapping for this isn't as obvious as the "Go to Definition" but you can always change that.

**Comment by bmxam** [comment]
Alright, thank you for the tips.
