### ISSUE TITLE
Remove docstring prefix in hover

### ISSUE THREAD

**Issue by letmaik** [hansec/vscode-fortran-ls#14]
When a variable is annotated with `!! description` then the hover also shows `!! ` including any whitespace between end of variable name and start of docstring. Why not cut this off and just display `description`?

**Comment by hansec** [comment]
Unfortunately, I am unable to reproduce this with my codebases. Can you provide an example? Any whitespace between the variable name and the docstring should be stripped (see below) so if it is not that is a bug in the LS.

For this code

```fortran
INTEGER :: var_w_trailing_wspace                 !! description
```

I get the following hover. Note, that the single leading space before `!!` is a formatting choice for consistency with subroutine/function hovers.

```fortran
INTEGER
 !! description
```

**Comment by letmaik** [comment]
You actually reproduced it! :) Maybe it's by-design then. I found it weird that `!! ` is included in the hover, that's all.

**Comment by hansec** [comment]
Got it. Yeah, that is just to distinguish the docstring using syntax highlighting in the hover.
