### ISSUE TITLE
Mouse-over issue with line continuations

### ISSUE THREAD

**Issue by mystery-e204** [hansec/vscode-fortran-ls#16]
The optional `&` at the beginning of the next line in a line continuation leads to incorrect mouse-over behavior. A mouse-over of `a` in the argument list of `routine_OK` shows `integer, intent(in)` while in `routine_TROUBLE` it shows `logical, intent(out)`.
I don't think it is an issue of the language server, as the type of all three arguments is correctly parsed and shown when typing `call routine_TROUBLE(...)` in the main program.

```Fortran
   subroutine routine_OK( &
      a, b, c)
      integer, intent(in)     :: a
      real,    intent(inout)  :: b
      logical, intent(out)    :: c
   end subroutine routine_OK

   subroutine routine_TROUBLE( &
      & a, b, c)
      integer, intent(in)     :: a
      real,    intent(inout)  :: b
      logical, intent(out)    :: c
   end subroutine routine_TROUBLE
```

**Comment by hansec** [comment]
Thanks for the report! This was actually an issue in the language server (see issue above). It should now be fixed in master and will be included in the next patch.
