### ISSUE TITLE
Syntax highlighting for hovers

### ISSUE THREAD

**Issue by letmaik** [hansec/vscode-fortran-ls#17]
Especially when hovering over a subroutine name then the big hover text with argument list and types is a bit daunting without syntax highlighting. If possible, it would be great if this was Fortran-highlighted.

**Comment by hansec** [comment]
Hmmmm, hover boxes should be highlighted. Can you tell me what other extensions you are using and give me an example? Do you ever see syntax highlighted hover content or is it always plain text?

I have noticed that sometimes VSCode generates its own hovers from the definition location and displays that region as non-highlighted text. However, when/why this happens doesn't appear to be too consistent. Although, I think generally it doesn't happen when the hover request returns a result.

**Comment by letmaik** [comment]
I have `gimly81.fortran` (fortran) installed. When I disable this and instead install `krvajalm.linter-gfortran` (Modern Fortran) then the highlighting works.

**Comment by AndreHorst** [comment]
I'm afraid there is an issue now. Somehow the hover-text is not working correctly anymore, but it was all working like a charm in the last version. Here are two examples:

![grafik](https://user-images.githubusercontent.com/25814609/78101661-80478880-73e8-11ea-8f77-cc79c4f2db5b.png)

![grafik](https://user-images.githubusercontent.com/25814609/78101704-ab31dc80-73e8-11ea-9fc6-5adf20a08cdd.png)

My extensions are unchanged:

- krvajalm.linter-gfortran v2.1.1
- hansec.fortran-ls v0.6.0 (why 0.6.0 anyway? It's working great!)
- ekibun.fortranbreaker v0.0.4

**Comment by hansec** [comment]
@AndreHorst Thanks for the report! Sorry about that. I pushed a patch (1.11.1) to fix this a little while ago. See [fortls issue #159](https://github.com/hansec/fortran-language-server/issues/159) for more information.
