### ISSUE TITLE
Peek Definition not working

### ISSUE THREAD

**Issue by nyckmaia** [hansec/vscode-fortran-ls#18]
I installed today two VS Code extensions from VS Code extensions button:

1. Modern Fortran 0.4.5
2. FORTRAN IntelliSense 0.6.0

I got the Syntax highlighting from the Modern Fortran but the Peek Definition from Fortran IntelliSense is not working. 

What is happening?

**My system:**
Windows 10 x64
VS Code 1.38.1

**Comment by hansec** [comment]
Did you install the [underlying language server](https://github.com/hansec/fortran-language-server)? This package relies on the language server for all of its functionality.

**Comment by nyckmaia** [comment]
Yes...it is installed! But not working yet...

What more I have to do?

**Comment by michaelkonecny** [comment]
In the Fortran IntelliSense extension settings, did you properly set the path to the fortls executable?

**Comment by nyckmaia** [comment]
Thank you @michaelkonecny ! Now it's working great!

**Comment by nyckmaia** [comment]
I'm using this extension in VS Code.
Is possible to use it in Visual Studio Enterprise 2019? How can i configure it in this case?

**Comment by michaelkonecny** [comment]
Not yet, AFAIK.
I have created an extension for Visual Studio 2017: https://github.com/michaelkonecny/vs-fortran-ls-client
but it needs a lot of improvement
(unfortunately, my work setup didn't allow me to install a fresh enough version of Visual Studio which would support these extensions, so I couldn't work on it)
I'm planning on updating it for VS2019, but I won't be able to do it until I get a bit of free time at work, so probably some time around the beginning of next year...

**Comment by nyckmaia** [comment]
Thank you a lot @michaelkonecny !
