### ISSUE TITLE
BUG: fortls 1.11.0 breaks hovering support

### ISSUE THREAD

**Issue by gnikit** [hansec/vscode-fortran-ls#20]
I think that `fortls` release `1.11.0` which added some stuff with regards to hover has caused the vscode package to break.

Hover reads: `[object Object]`

I think this extension in general might need to be brought up to speed with the latest version of `fortls` since some of the newer options might not have been included.

**Comment by hansec** [comment]
Thanks for the report! Sorry about that. I have identified the problem and will be pushing a patch release to fix this shortly. See [fortls issue #159](https://github.com/hansec/fortran-language-server/issues/159) for more information.

**Comment by gnikit** [comment]
> Thanks for the report! Sorry about that. I have identified the problem and will be pushing a patch release to fix this shortly. See [fortls issue #159](https://github.com/hansec/fortran-language-server/issues/159) for more information.

Awesome! Thanks a lot for the quick fix.
