### ISSUE TITLE
Hover syntax highlighting colour not working

### ISSUE THREAD

**Issue by gnikit** [hansec/vscode-fortran-ls#21]
Hi, with the recent update to `fortls 1.11.1` something must have changed causing this weird colouring for the type of a variable when hovering.

![Screenshot from 2020-04-04 03-28-47](https://user-images.githubusercontent.com/16143716/78416983-6fd02180-7625-11ea-8788-b7e07c909477.png)

**Comment by pedro-ricardo** [comment]
Hello there @hansec 
Can you reopen this please?

krvajal (the owner of Modern Fortran) stopped responding a while ago so I released a new version with some fixes, and now the new version of the extension goes with the name `pedro-ricardo.linter-gfortran`
Therefore this fix b4ffed1 stop working and a similar bug happens [like this one](https://github.com/krvajal/vscode-fortran-support/issues/182)

**Comment by pedro-ricardo** [comment]
As he might comeback I suggest you yo add an `or` there, not overwrite.
Thank you :+1:
