### ISSUE TITLE
Can this plugin support visual studio as well?

### ISSUE THREAD

**Issue by PhysicsPlasma** [hansec/vscode-fortran-ls#4]
Thanks!

**Comment by michaelkonecny** [comment]
No, plugins for VS and for VS Code are completely different.
The two editors actually have little in common.

I made this extension for VS: 
https://github.com/michaelkonecny/vs-fortran-ls-client
keep in mind, however, that it's a work in progress.

**Comment by hansec** [comment]
As @michaelkonecny said plugins are not compatible between VSCode and VS. However, he has been working hard on the VS plugin so I encourage you to check it out!
