### ISSUE TITLE
[Suggestion] Implementation of deferred procedure

### ISSUE THREAD

**Issue by bmxam** [hansec/vscode-fortran-ls#8]
Let's say we have an abstract super class A that declares some 'deferred' procedures. It would be great that, when we create a sub class that inherits from A, a simple click on some kind of notification let's us implement the deferred procedure.

**Comment by hansec** [comment]
Initial support for this feature was added in version 1.7.0 of the language server and version 0.4.0 of the VSCode extension. This is a fairly complicated feature so I am sure there will be cases where problems arise, so please report any issues to the [language server repository](https://github.com/hansec/fortran-language-server). Thanks again for the suggestion and I hope you find the new features useful!
